### ISSUE TITLE
undefined method `coverage' 

### ISSUE THREAD

**Issue by sajusat** [vicentllongo/simplecov-json#13]
```
/usr/local/bundle/gems/simplecov-json-0.2/lib/simplecov-json.rb:16:in `block in format': undefined method `coverage' for #<SimpleCov::SourceFile:0x000056089302af48> (NoMethodError)
Did you mean?  coverage_data
	from /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `each'
	from /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `each'
	from /usr/local/bundle/gems/simplecov-json-0.2/lib/simplecov-json.rb:11:in `format'
	from /usr/local/bundle/gems/simplecov-0.18.2/lib/simplecov/result.rb:49:in `format!'
	from /usr/local/bundle/gems/simplecov-0.18.2/lib/simplecov/configuration.rb:196:in `block in at_exit'
	from /usr/local/bundle/gems/simplecov-0.18.2/lib/simplecov.rb:201:in `run_exit_tasks!'
	from /usr/local/bundle/gems/simplecov-0.18.2/lib/simplecov/defaults.rb:31:in `block in <top (required)>'
```

Can you please fix it. I think it is related to a pull request that is already submitted. Can you please release the gem with the fix?
Sonarqube expects this output, it is not accepting the simplecov's default `.resultset.json` output.

**Comment by vicentllongo** [comment]
Fixed after https://github.com/vicentllongo/simplecov-json/pull/12
